# Generated by Django 5.2.8 on 2025-11-30 17:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Carrera')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculadora.carrera', verbose_name='Carrera')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Ramo')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('semestre', models.IntegerField(default=1, verbose_name='Semestre')),
                ('anio_academico', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto')], default='1', max_length=1, verbose_name='Año en el que vas')),
                ('asistencia', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Asistencia (%)')),
                ('nota_objetivo', models.FloatField(default=3.95, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(7.0)], verbose_name='Nota Objetivo')),
                ('is_historical', models.BooleanField(default=False, verbose_name='Es Histórico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramos', to='calculadora.carrera', verbose_name='Carrera')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ramos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ramo',
                'verbose_name_plural': 'Ramos',
                'ordering': ['-is_historical', 'anio_academico', 'semestre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Evaluación')),
                ('tipo', models.CharField(choices=[('SOLEMNE', 'Solemne'), ('TALLER', 'Taller'), ('CONTROL', 'Control'), ('LABORATORIO', 'Laboratorio'), ('PROYECTO', 'Proyecto'), ('OTRO', 'Otro')], default='SOLEMNE', max_length=20, verbose_name='Tipo')),
                ('ponderacion', models.FloatField(help_text='Porcentaje de la nota (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ponderación')),
                ('nota', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(7.0)], verbose_name='Nota')),
                ('ramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='calculadora.ramo', verbose_name='Ramo')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
    ]
