# Generated by Django 5.2.8 on 2025-11-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0002_alter_ramo_anio_academico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['tipo', 'nombre'], 'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
    ]
